name: Análise de Segurança com Bandit

on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Rodar Bandit
        run: |
          bandit -r . -ll -o bandit-relatorio.txt -f txt
